# Generated by Django 4.2.7 on 2023-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_race_photo_alter_driver_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceparticipant',
            name='lapTime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='qualifyLapTime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='trainLapTime',
            field=models.DurationField(),
        ),
    ]
