# Generated by Django 4.2.7 on 2023-11-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_raceparticipant_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='podiums',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
    ]
