# Generated by Django 4.2.7 on 2024-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_driver_podiums_remove_driver_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='colour',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
