# Generated by Django 4.2.7 on 2024-03-07 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_raceparticipant_laptime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceparticipant',
            name='videoURL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='lapTime',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{2}:?[0-9]{2}.[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='qualifyLapTime',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{2}:?[0-9]{2}.[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='trainLapTime',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{2}:?[0-9]{2}.[0-9]{4}')]),
        ),
        migrations.CreateModel(
            name='RaceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('videoURL', models.URLField(null=True)),
                ('resolution', models.TextField()),
                ('drivers', models.ManyToManyField(to='api.driver')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.race')),
            ],
        ),
    ]
