# Generated by Django 4.2.7 on 2024-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_raceparticipant_videourl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
