# Generated by Django 4.2.7 on 2024-03-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
