# Generated by Django 4.2.7 on 2024-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceparticipant',
            name='fastLap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceparticipant',
            name='grandChelem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceparticipant',
            name='theFasto',
            field=models.BooleanField(default=False),
        ),
    ]
