# Generated by Django 4.2.7 on 2023-11-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('lapTime', models.TimeField()),
                ('qualifyLapTime', models.TimeField()),
                ('trainLapTime', models.TimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.race')),
            ],
        ),
    ]
