# Generated by Django 4.2.7 on 2023-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceparticipant',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
